version: '3'
services:
  coredns:
    image: coredns/coredns:1.1.4
    command:
    - -conf
    - /Corefile
    ports:
    - "53:53"
    - "53:53/udp"
    volumes:
    - ./template/Corefile:/Corefile
    - ./template/example.com:/example.com
    restart: always
